"""Encryption at rest for Plaid access tokens.

Fernet (AES-128-CBC + HMAC) with a key kept in the .env file next to the other
secrets. The key is generated automatically the first time a token needs to be
stored, and appended to the .env so it survives restarts. Encrypted values are
prefixed "enc:v1:" so legacy plaintext rows are recognized and re-encrypted the
next time they are touched.

This protects the tokens in the SQLite file (backups, copies, a lost laptop);
someone who has BOTH the database and the .env has the key too, which is the
accepted trust boundary for a local-first app.
"""

from __future__ import annotations

from cryptography.fernet import Fernet

from .config import BACKEND_DIR, REPO_ROOT, settings

PREFIX = "enc:v1:"


def _persist_key(key: str) -> None:
    """Append the generated key to whichever .env this instance uses."""
    for candidate in (REPO_ROOT / ".env", BACKEND_DIR / ".env"):
        if candidate.exists():
            with candidate.open("a", encoding="utf-8") as fh:
                fh.write(f"\n# Generated by Tally: encrypts Plaid tokens at rest.\n"
                         f"TALLY_ENCRYPTION_KEY={key}\n")
            return
    target = REPO_ROOT / ".env"
    target.write_text(f"TALLY_ENCRYPTION_KEY={key}\n", encoding="utf-8")


def _fernet() -> Fernet:
    if not settings.TALLY_ENCRYPTION_KEY:
        key = Fernet.generate_key().decode()
        _persist_key(key)
        settings.TALLY_ENCRYPTION_KEY = key
    return Fernet(settings.TALLY_ENCRYPTION_KEY.encode())


def encrypt_token(plain: str) -> str:
    return PREFIX + _fernet().encrypt(plain.encode()).decode()


def is_encrypted(value: str) -> bool:
    return value.startswith(PREFIX)


def decrypt_token(value: str) -> str:
    """Decrypt a stored value; legacy plaintext comes back unchanged."""
    if not is_encrypted(value):
        return value
    return _fernet().decrypt(value[len(PREFIX):].encode()).decode()
